### ISSUE TITLE
Clarify Licence

### ISSUE THREAD

**Issue by fabianschwarzfritz** [juliangarnier/juliangarnier.com#2]
This website looks pretty cool! Fun idea :+1: . 
Under which licence is the source code of this repository? I cannot find a LICENCE file. Could you please clarify?

**Comment by fabianschwarzfritz** [comment]
Any news from this?

**Comment by juliangarnier** [comment]
There 6c087c9d149e68bcc05c38d9777b33b6cf85c632 ✌️

**Comment by fabianschwarzfritz** [comment]
Thanks
